### ISSUE TITLE
Not getting any errors

### ISSUE THREAD

**Issue by Mobilpadde** [kritzware/node-twitchbot#13]
Well, for some reason, I'm able to connect but nothing else? And the weird part is, that I'm not getting any errors? 😭

**Comment by kritzware** [comment]
Can you show me your code? Don't forget to hide the oauth token!

**Comment by Mobilpadde** [comment]
Yea, of course!

```js
// bot.js
const TwitchBot = require("node-twitchbot");

module.exports = {
	Start: function(channel){
		const bot = new TwitchBot({
			username: "mobilpadde",
			oauth: "oauth:smiley",
			channel: channel,
		});

		let msgCallbacks = [];
		bot.connect().then(() => {
			console.log("connected");

			bot.listen((err, chatter) => {
				console.log(err, chatter);
				if(err){
					console.log(err);
					return;
				}

				msgCallbacks.forEach(cb => cb(chatter));
				console.log(chatter);
			});
		}).catch(err => {
			console.log(err);
		});

		return {
			listen: {
				msg: (cb) => {
					msgCallbacks.push(cb);
				}
			}
		};
	}
};

// server.js
const Bot = require("./bot");
new Bot.Start("mobilpadde");
```

**Comment by kritzware** [comment]
[1]~I just tested your code myself and it works fine for me. Double check that the credentials you're providing are correct!~ [2]~I was using the wrong version and now get the error. Looking into it again.~

<b> EDIT 3:</b> I'm not getting the error with the same code anymore (I was typing my messages into the wrong channel 😆). Double check that the credentials you're providing are correct!

**Comment by Mobilpadde** [comment]
Nop, still doesn't work. I'm properly connected, but it won't give me any feedback at all..?

Also, it says it's still able to connect, even if I type the wrong username associated with the token?

**Comment by kritzware** [comment]
Try updating the package to version 2.0.4 if you haven't already. If that doesn't fix it, I'll look into this issue in more detail! 👍

**Comment by Mobilpadde** [comment]
I'm already using `2.0.4` 😢

**Comment by kritzware** [comment]
Something else you can try, remove the package completely (make sure it removes the `irc/` dependency in `node_modules`) rather than upgrading and install again 🤔

**Comment by Mobilpadde** [comment]
Just reinstalled everything, by removing the `node_modules` completely, and then `npm i`, but alas, no luck. :c

**Comment by kritzware** [comment]
Is your bot/your account able to type in twitch chat normally?

I made a new project using the latest version of the package and the code you provided earlier, and it works fine for me 🤔

**Comment by Mobilpadde** [comment]
Hmm, it can say stuff, just not retrieve it? 😿

**Comment by kritzware** [comment]
Have you changed the code you posted earlier? If so post your newer code 🤔

**Comment by Mobilpadde** [comment]
Only did a `bot.msg` within the `then`, other than that, nope 😢

**Comment by kritzware** [comment]
What `node --version` are you using?

**Comment by Mobilpadde** [comment]
I'm using `7.5.0`, but for some reason, I'd forgot to close my app, so I received the `Kappa` you wrote? So, does this mean, that I can only get messages not from myself? Well, it'd make sense, but still?

**Comment by kritzware** [comment]
I did try that when I was testing (If it displays the bot messages) and it seemed to work fine as well. 

I'll look into this issue though, and perhaps add a `listen()` method specifically for the bot as well to separate it out. For now, assuming it works with your project, I'd recommend making another Twitch account to use as a bot.
