### ISSUE TITLE
Some chatter objects have no 'user' value

### ISSUE THREAD

**Issue by kitchentiger** [kritzware/node-twitchbot#16]
There are many instances where chatter objects have a blank string value for the user property, even though they come from a user. I've tried this in both Windows and Ubuntu. It always seems to be the same user names, but I can't see anything particularly interesting or common about them.

**Comment by kritzware** [comment]
Thanks for this report, I'll take a look into it! 👍

**Comment by kritzware** [comment]
If you know the usernames, could you post them here @bmm85?

**Comment by kitchentiger** [comment]
Join up a major channel like summit1g for 5 minutes. Here are a few I just found:

Obsoleete
Deadboy12345
Extexius

Every message they post is like this.

**Comment by kritzware** [comment]
I've ran some tests and here are two IRC events, one where the `display-name=` is undefined and one where it is given.

```
  { command: '@badges=subscriber/3,premium/1;color=#FF0000;display-name=RyeZ33;emotes=;id=247ad2ed-94d7-4ec4-b686-d1605cea52e2;
  mod=0;room-id=26490481;sent-ts=1493426546056;subscriber=1;tmi-sent-ts=1493426544839;turbo=0;user-id=53667083;user-type=',
  rawCommand: '@badges=subscriber/3,premium/1;color=#FF0000;display-name=RyeZ33;emotes=;id=247ad2ed-94d7-4ec4-b686-d1605cea52e2;
  mod=0;room-id=26490481;sent-ts=1493426546056;subscriber=1;tmi-sent-ts=1493426544839;turbo=0;user-id=53667083;user-type=',
  commandType: 'normal',
  args: [ 'ryez33!ryez33@ryez33.tmi.twitch.tv PRIVMSG #summit1g :ROFL' ] }
```

```
  { command: '@badges=subscriber/0,premium/1;color=;display-name=;emotes=;id=5b3543c2-f534-4bd6-ab7d-5cb6cc2f94fb;
  mod=0;room-id=26490481;sent-ts=1493426658724;subscriber=1;tmi-sent-ts=1493426662020;turbo=0;user-id=76439674;user-type=',
  rawCommand: '@badges=subscriber/0,premium/1;color=;display-name=;emotes=;id=5b3543c2-f534-4bd6-ab7d-5cb6cc2f94fb;
  mod=0;room-id=26490481;sent-ts=1493426658724;subscriber=1;tmi-sent-ts=1493426662020;turbo=0;user-id=76439674;user-type=',
  commandType: 'normal',
  args: [ 'obsoleete!obsoleete@obsoleete.tmi.twitch.tv PRIVMSG #summit1g :YOU JUKED HIM LOOOOOOOOOOOOOOOOL' ] }
```

The second event has an undefined `display-name=` but does include the name (in lowercase) in the `args` part of the message. Either this is a Twitch bug or something is wrong with the IRC library? 

For now, I can just get the lowercase name if the `display-name` is not given. Would a temporary fix like this work for you?

**Comment by kitchentiger** [comment]
Yeah that would be very helpful. I wonder what makes that happen for certain users. 

Just FYI it is not only an issue with this module. I installed the tmi.js module and found the same issue. Here is the userstate object in that module:

{
    'badges': { 'broadcaster': '1', 'warcraft': 'horde' },
    'color': '#FFFFFF',
    'display-name': 'Schmoopiie',
    'emotes': { '25': [ '0-4' ] },
    'mod': true,
    'room-id': '58355428',
    'subscriber': false,
    'turbo': true,
    'user-id': '58355428',
    'user-type': 'mod',
    'emotes-raw': '25:0-4',
    'badges-raw': 'broadcaster/1,warcraft/horde',
    'username': 'schmoopiie',
    'message-type': 'action'
}

My guess would be that username is going to be the safest bet and it is probably extracted from the string: obsoleete!obsoleete@obsoleete.tmi.twitch.tv, thought I don't have enough knowledge of the raw data to say for sure. I'm sure you would know better.

**Comment by kitchentiger** [comment]
I have come across this comment (https://discuss.dev.twitch.tv/t/display-name-not-reliable/2277):

> It's probably users that don't have the display name customized that don't show up. I don't think the display name tag is supposed to be used as primary source for the name, just for display purposes, if it is there. If it's not there, just use the all lowercase name and capitalize the first letter, which I think is the default behaviour (or keep it all lowercase, whatever you prefer for your application).

Given this, I think adhering to this for display purposes is important. If display-name is not sent by the server, use the lower case version and capitalize the first letter (for display only). The user's ID is obviously the only reliable way to store permanent user data now that Twitch allows user name changes now.

**Comment by kritzware** [comment]
Interesting, thanks for linking that forum post. 

I might just get the lower case name all the time as well then and use that as the `chatter.username` attribute, and move the display name to a new chatter attribute, `chatter.display_name`. If the `display-name` isn't given in the IRC message, I'll take the lower case version and capitalise the first letter 👍 

I'm going to be pretty busy the next few days but I'll try and push a fix when I have some free time!

**Comment by kritzware** [comment]
This is fixed in the upcoming [V2 release](https://github.com/kritzware/node-twitchbot/tree/v2) 👍
