### ISSUE TITLE
Block-scoped declarations (let, const, etc) break server

### ISSUE THREAD

**Issue by aarohmankad** [kritzware/node-twitchbot#8]
I've found a solution that involves `"use strict";` that fixes it.

I'm not sure as to the cause of it, but from what I've observed, it fixes the issue for people who are encountering it and does nothing to those for whom it was already working.

![Block-scoped declarations (let, const, function, class) not yet supported outside strict mode](https://cloud.githubusercontent.com/assets/3311321/19369078/0f8cb226-9158-11e6-83e6-4c71977b6b3f.png)

**Comment by kritzware** [comment]
This happens on older node versions, which can be easily supported via the solution you have recommended, nice! 👍
